language: ruby
rvm:
  - 2.5.1
jobs:
  include:
    - stage: "Inspections"
      name: "Rubocop"
      script: bundle exec rubocop
    - stage: "Tests"
      name: "Back-end specs - Controllers"
      script: bundle exec rspec spec/brewery_app_spec.rb
    - stage: "Tests"
      name: "Back-end specs - Models"
      script: bundle exec rspec spec/models
